import { FormEvent, useEffect, useState } from "react";
import { NotificationPreference, getNotificationQueueStatus, useNotificationPreferences, useUpdateNotificationPreferences } from "@/hooks/notifications";
import { checkPermissions, requestPermissions, syncServerNotificationsDetailed } from "@/utils/notifs";
import { useUser } from "@/hooks/user";

const defaultPrefs: NotificationPreference = {
  pushEnabled: true,
  remindersEnabled: true,
  summaryCadence: "daily",
  summaryTime: "08:00",
  weeklyDay: 1,
  utcOffsetMinutes: new Date().getTimezoneOffset()
};

function Toggle({ checked, onChange, disabled }: { checked: boolean; onChange: (v: boolean) => void; disabled?: boolean }) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      disabled={disabled}
      onClick={() => onChange(!checked)}
      className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full transition-colors duration-200 disabled:opacity-40 ${checked ? "bg-accent-blue" : "bg-silver-300 dark:bg-vulcan-700"}`}
    >
      <span className={`pointer-events-none mt-0.5 inline-block h-5 w-5 rounded-full bg-white shadow-sm transition-transform duration-200 ${checked ? "translate-x-5" : "translate-x-0.5"}`} />
    </button>
  );
}

export default function ServerNotificationSettings() {
  const user = useUser();
  const isDeveloper = Boolean(user.data?.developer);
  const prefsQuery = useNotificationPreferences();
  const updatePrefs = useUpdateNotificationPreferences();
  const [form, setForm] = useState<NotificationPreference>(defaultPrefs);
  const [status, setStatus] = useState("");
  const [permissionState, setPermissionState] = useState<string>("default");

  useEffect(() => {
    if (!prefsQuery.isSuccess || !prefsQuery.data) return;
    setForm({ ...defaultPrefs, ...prefsQuery.data });
  }, [prefsQuery.isSuccess, prefsQuery.data]);

  useEffect(() => {
    checkPermissions()
      .then((permission) => setPermissionState(permission.display))
      .catch(() => setPermissionState("default"));
  }, []);

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setStatus("");

    try {
      await updatePrefs.mutateAsync({
        pushEnabled: form.pushEnabled,
        remindersEnabled: form.remindersEnabled,
        summaryCadence: form.summaryCadence,
        summaryTime: form.summaryTime,
        weeklyDay: form.weeklyDay,
        utcOffsetMinutes: new Date().getTimezoneOffset()
      });
      setStatus("Notification preferences saved.");
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Unable to save notification preferences.";
      setStatus(message);
    }
  };

  const checkNow = async () => {
    setStatus("");
    try {
      const queue = await getNotificationQueueStatus();
      const result = await syncServerNotificationsDetailed();
      setPermissionState(result.permission);
      if (result.pending === 0) {
        const nextTime = queue.nextScheduledFor ? new Date(queue.nextScheduledFor).toLocaleString() : "none";
        setStatus(`No due notifications now. Upcoming: ${queue.upcoming}. Next scheduled: ${nextTime}.`);
        return;
      }

      if (result.permission !== "granted") {
        setStatus(`Found ${result.pending} due now, but notification permission is '${result.permission}'. Upcoming: ${queue.upcoming}.`);
        return;
      }

      setStatus(`Found ${result.pending} due now. Delivered ${result.delivered}. Upcoming: ${queue.upcoming}.`);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Unable to check server notifications.";
      setStatus(message);
    }
  };

  const enableNotifications = async () => {
    setStatus("");
    try {
      const current = await checkPermissions();
      setPermissionState(current.display);
      if (current.display === "granted") {
        setStatus("Notifications are already enabled.");
        return;
      }

      const requested = await requestPermissions();
      setPermissionState(requested.display);
      setStatus(
        requested.display === "granted"
          ? "Notifications enabled."
          : `Notification permission is '${requested.display}'. Enable it in browser/macOS settings.`
      );
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Unable to request notification permission.";
      setStatus(message);
    }
  };

  return (
    <div className="flex flex-col gap-4">
      <div>
        <h2 className="text-base font-semibold text-primary">Server Notifications</h2>
        <p className="text-sm text-muted">Notifications are generated by server rules and delivered to this device.</p>
      </div>

      <form onSubmit={submit} className="flex flex-col gap-4">
        <div className="flex flex-col gap-3">
          <div className="flex items-center justify-between gap-4">
            <span className="text-sm text-primary">Enable server notifications</span>
            <Toggle checked={form.pushEnabled} onChange={(v) => setForm({ ...form, pushEnabled: v })} />
          </div>
          <div className="flex items-center justify-between gap-4">
            <span className={`text-sm ${form.pushEnabled ? "text-primary" : "text-muted"}`}>Remind me before task due times</span>
            <Toggle checked={form.remindersEnabled} onChange={(v) => setForm({ ...form, remindersEnabled: v })} disabled={!form.pushEnabled} />
          </div>
        </div>

        <div className="flex flex-wrap gap-3">
          <label className="flex flex-col gap-1 text-sm text-primary">
            Summary cadence
            <select
              value={form.summaryCadence}
              onChange={(event) => setForm({ ...form, summaryCadence: event.target.value as NotificationPreference["summaryCadence"] })}
              className="rounded-lg border border-(--surface-border) bg-silver-200 dark:bg-vulcan-950 px-3 py-2 text-sm text-primary"
              disabled={!form.pushEnabled}
            >
              <option value="off">Off</option>
              <option value="daily">Daily (tasks due today)</option>
              <option value="weekly">Weekly (next 7 days)</option>
            </select>
          </label>

          {form.summaryCadence === "weekly" && (
            <label className="flex flex-col gap-1 text-sm text-primary">
              Weekly day
              <select
                value={String(form.weeklyDay)}
                onChange={(event) => setForm({ ...form, weeklyDay: Number(event.target.value) })}
                className="rounded-lg border border-(--surface-border) bg-silver-200 dark:bg-vulcan-950 px-3 py-2 text-sm text-primary"
                disabled={!form.pushEnabled}
              >
                <option value="0">Sunday</option>
                <option value="1">Monday</option>
                <option value="2">Tuesday</option>
                <option value="3">Wednesday</option>
                <option value="4">Thursday</option>
                <option value="5">Friday</option>
                <option value="6">Saturday</option>
              </select>
            </label>
          )}

          {form.summaryCadence !== "off" && (
            <label className="flex flex-col gap-1 text-sm text-primary">
              Summary time
              <input
                type="time"
                value={form.summaryTime}
                onChange={(event) => setForm({ ...form, summaryTime: event.target.value })}
                className="rounded-lg border border-(--surface-border) bg-silver-200 dark:bg-vulcan-950 px-3 py-2 text-sm text-primary"
                disabled={!form.pushEnabled}
              />
            </label>
          )}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            type="submit"
            className="rounded-lg bg-accent-blue px-3 py-2 text-sm font-semibold text-white shadow-xs shadow-accent-blue/30 hover:-translate-y-px transition disabled:opacity-70"
            disabled={updatePrefs.isPending || prefsQuery.isLoading}
          >
            {updatePrefs.isPending ? "Saving..." : "Save notification settings"}
          </button>
          {isDeveloper && (
            <button
              type="button"
              className="rounded-lg bg-accent-blue px-3 py-2 text-sm font-semibold text-white shadow-xs shadow-accent-blue/30 hover:-translate-y-px transition"
              onClick={checkNow}
            >
              Check now
            </button>
          )}
          {permissionState !== "granted" && (
            <button
              type="button"
              className="rounded-lg bg-accent-blue px-3 py-2 text-sm font-semibold text-white shadow-xs shadow-accent-blue/30 hover:-translate-y-px transition"
              onClick={enableNotifications}
            >
              Enable notifications
            </button>
          )}
          {status && <span className="text-sm text-muted">{status}</span>}
        </div>
      </form>
    </div>
  );
}
