import { FormEvent, useEffect, useState } from "react";
import { NotificationPreference, getNotificationQueueStatus, useNotificationPreferences, useUpdateNotificationPreferences } from "@/hooks/notifications";
import { checkPermissions, requestPermissions, syncServerNotificationsDetailed } from "@/utils/notifs";
import { useUser } from "@/hooks/user";

const defaultPrefs: NotificationPreference = {
  pushEnabled: true,
  remindersEnabled: true,
  summaryCadence: "daily",
  summaryTime: "08:00",
  weeklyDay: 1,
  utcOffsetMinutes: new Date().getTimezoneOffset()
};

export default function ServerNotificationSettings() {
  const user = useUser();
  const isDeveloper = Boolean(user.data?.developer);
  const prefsQuery = useNotificationPreferences();
  const updatePrefs = useUpdateNotificationPreferences();
  const [form, setForm] = useState<NotificationPreference>(defaultPrefs);
  const [status, setStatus] = useState("");
  const [permissionState, setPermissionState] = useState<string>("default");

  useEffect(() => {
    if (!prefsQuery.isSuccess || !prefsQuery.data) return;
    setForm({ ...defaultPrefs, ...prefsQuery.data });
  }, [prefsQuery.isSuccess, prefsQuery.data]);

  useEffect(() => {
    checkPermissions()
      .then((permission) => setPermissionState(permission.display))
      .catch(() => setPermissionState("default"));
  }, []);

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setStatus("");

    try {
      await updatePrefs.mutateAsync({
        pushEnabled: form.pushEnabled,
        remindersEnabled: form.remindersEnabled,
        summaryCadence: form.summaryCadence,
        summaryTime: form.summaryTime,
        weeklyDay: form.weeklyDay,
        utcOffsetMinutes: new Date().getTimezoneOffset()
      });
      setStatus("Notification preferences saved.");
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Unable to save notification preferences.";
      setStatus(message);
    }
  };

  const checkNow = async () => {
    setStatus("");
    try {
      const queue = await getNotificationQueueStatus();
      const result = await syncServerNotificationsDetailed();
      setPermissionState(result.permission);
      if (result.pending === 0) {
        const nextTime = queue.nextScheduledFor ? new Date(queue.nextScheduledFor).toLocaleString() : "none";
        setStatus(`No due notifications now. Upcoming: ${queue.upcoming}. Next scheduled: ${nextTime}.`);
        return;
      }

      if (result.permission !== "granted") {
        setStatus(`Found ${result.pending} due now, but notification permission is '${result.permission}'. Upcoming: ${queue.upcoming}.`);
        return;
      }

      setStatus(`Found ${result.pending} due now. Delivered ${result.delivered}. Upcoming: ${queue.upcoming}.`);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Unable to check server notifications.";
      setStatus(message);
    }
  };

  const enableNotifications = async () => {
    setStatus("");
    try {
      const current = await checkPermissions();
      setPermissionState(current.display);
      if (current.display === "granted") {
        setStatus("Notifications are already enabled.");
        return;
      }

      const requested = await requestPermissions();
      setPermissionState(requested.display);
      setStatus(
        requested.display === "granted"
          ? "Notifications enabled."
          : `Notification permission is '${requested.display}'. Enable it in browser/macOS settings.`
      );
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Unable to request notification permission.";
      setStatus(message);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div>
        <h2 className="text-lg font-semibold text-primary">Server Notifications</h2>
        <p className="text-sm text-muted">Notifications are generated by server rules and delivered to this device.</p>
      </div>

      <form onSubmit={submit} className="grid gap-3">
        <label className="inline-flex items-center gap-2 text-sm text-primary">
          <input
            type="checkbox"
            checked={form.pushEnabled}
            onChange={(event) => setForm({ ...form, pushEnabled: event.target.checked })}
          />
          Enable server notifications
        </label>

        <label className="inline-flex items-center gap-2 text-sm text-primary">
          <input
            type="checkbox"
            checked={form.remindersEnabled}
            onChange={(event) => setForm({ ...form, remindersEnabled: event.target.checked })}
            disabled={!form.pushEnabled}
          />
          Remind me before task due times
        </label>

        <label className="flex flex-col gap-1 text-sm text-primary">
          Summary cadence
          <select
            value={form.summaryCadence}
            onChange={(event) => setForm({ ...form, summaryCadence: event.target.value as NotificationPreference["summaryCadence"] })}
            className="rounded-lg border border-accent-blue/20 bg-white px-3 py-2 text-sm"
            disabled={!form.pushEnabled}
          >
            <option value="off">Off</option>
            <option value="daily">Daily (tasks due today)</option>
            <option value="weekly">Weekly (next 7 days)</option>
          </select>
        </label>

        {form.summaryCadence !== "off" && (
          <label className="flex flex-col gap-1 text-sm text-primary">
            Summary time
            <input
              type="time"
              value={form.summaryTime}
              onChange={(event) => setForm({ ...form, summaryTime: event.target.value })}
              className="w-fit rounded-lg border border-accent-blue/20 bg-white px-3 py-2 text-sm"
              disabled={!form.pushEnabled}
            />
          </label>
        )}

        {form.summaryCadence === "weekly" && (
          <label className="flex flex-col gap-1 text-sm text-primary">
            Weekly day
            <select
              value={String(form.weeklyDay)}
              onChange={(event) => setForm({ ...form, weeklyDay: Number(event.target.value) })}
              className="rounded-lg border border-accent-blue/20 bg-white px-3 py-2 text-sm"
              disabled={!form.pushEnabled}
            >
              <option value="0">Sunday</option>
              <option value="1">Monday</option>
              <option value="2">Tuesday</option>
              <option value="3">Wednesday</option>
              <option value="4">Thursday</option>
              <option value="5">Friday</option>
              <option value="6">Saturday</option>
            </select>
          </label>
        )}

        <div className="flex items-center gap-2">
          <button
            type="submit"
            className="rounded-lg bg-accent-blue px-3 py-2 text-sm font-semibold text-white"
            disabled={updatePrefs.isPending || prefsQuery.isLoading}
          >
            {updatePrefs.isPending ? "Saving..." : "Save notification settings"}
          </button>
          {isDeveloper && (
            <button
              type="button"
              className="rounded-lg border border-accent-blue/25 px-3 py-2 text-sm font-semibold text-primary"
              onClick={checkNow}
            >
              Check now
            </button>
          )}
          {permissionState !== "granted" && (
            <button
              type="button"
              className="rounded-lg border border-accent-blue/25 px-3 py-2 text-sm font-semibold text-primary"
              onClick={enableNotifications}
            >
              Enable notifications
            </button>
          )}
          {status && <span className="text-sm text-muted">{status}</span>}
        </div>
      </form>
    </div>
  );
}
